version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .spotify_matcher/flaskr/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    env_file: .env
    command: poetry run gunicorn -b 0.0.0.0:5000 spotify_matcher.flaskr:app
    volumes:
      - .:/app  # Mount current directory for live reloads
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    networks:
      - backend

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    restart: unless-stopped
    env_file: .env
    command: poetry run python -m celery -A spotify_matcher.flaskr.tasks worker -l info -P solo
    volumes:
      - .:/app  # Mount current directory for live reloads
    depends_on:
      - db
      - redis
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
