version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    restart: unless-stopped
    env_file: .env
    command: poetry run flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    networks:
      - backend

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    restart: unless-stopped
    command: poetry run python -m celery -A spotify_matcher.flaskr.tasks worker -l info -P solo
    depends_on:
      - db
      - redis
    networks:
      - backend


  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  postgres_data:

networks:
  backend:
